### ISSUE TITLE
unmet dependency color, npm start 

### ISSUE THREAD

**Issue by JustFly1984** [jxnblk/paths#15]
this is log file

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.11.2
3 info using node@v0.12.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart paths@1.0.0
6 info start paths@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info paths@1.0.0 Failed to exec start script
9 verbose stack Error: paths@1.0.0 start: `webpack-dev-server --progress --colors`
9 verbose stack spawn ENOENT
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid paths@1.0.0
11 verbose cwd /Users/justfly/sandbox/paths
12 error Darwin 14.3.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.6
15 error npm  v2.11.2
16 error file sh
17 error code ELIFECYCLE
18 error errno ENOENT
19 error syscall spawn
20 error paths@1.0.0 start: `webpack-dev-server --progress --colors`
20 error spawn ENOENT
21 error Failed at the paths@1.0.0 start script 'webpack-dev-server --progress --colors'.
21 error This is most likely a problem with the paths package,
21 error not with npm itself.
21 error Tell the author that this fails on your system:
21 error     webpack-dev-server --progress --colors
21 error You can get their info via:
21 error     npm owner ls paths
21 error There is likely additional logging output above.
22 verbose exit [ 1, true ]

**Comment by jxnblk** [comment]
I'm not really sure what's happening here. I am using npm 3, so I'll double check and make sure all the dependencies are in package.json.
